export var IVA_PERCENTAGE_CODE_ENUM;
(function (IVA_PERCENTAGE_CODE_ENUM) {
    IVA_PERCENTAGE_CODE_ENUM["IVA_0"] = "0";
    IVA_PERCENTAGE_CODE_ENUM["IVA_12"] = "2";
    IVA_PERCENTAGE_CODE_ENUM["IVA_14"] = "3";
    IVA_PERCENTAGE_CODE_ENUM["IVA_15"] = "4";
    IVA_PERCENTAGE_CODE_ENUM["IVA_5"] = "5";
    IVA_PERCENTAGE_CODE_ENUM["NO_OBJETO_IVA"] = "6";
    IVA_PERCENTAGE_CODE_ENUM["EXENTO_IVA"] = "7";
    IVA_PERCENTAGE_CODE_ENUM["IVA_DIFERENCIADO"] = "8";
    IVA_PERCENTAGE_CODE_ENUM["IVA_13"] = "10";
})(IVA_PERCENTAGE_CODE_ENUM || (IVA_PERCENTAGE_CODE_ENUM = {}));
