export var PAYMENT_METHOD_CODE_ENUM;
(function (PAYMENT_METHOD_CODE_ENUM) {
    PAYMENT_METHOD_CODE_ENUM["SIN_UTILIZACION_DEL_SISTEMA_FINANCIERO"] = "01";
    PAYMENT_METHOD_CODE_ENUM["COMPENSACION_DE_DEUDAS"] = "15";
    PAYMENT_METHOD_CODE_ENUM["TARJETA_DE_DEBITO"] = "16";
    PAYMENT_METHOD_CODE_ENUM["DINERO_ELECTRONICO"] = "17";
    PAYMENT_METHOD_CODE_ENUM["TARJETA_PREPAGO"] = "18";
    PAYMENT_METHOD_CODE_ENUM["TARJETA_DE_CREDITO"] = "19";
    PAYMENT_METHOD_CODE_ENUM["OTROS_CON_SISTEMA_FINANCIERO"] = "20";
    PAYMENT_METHOD_CODE_ENUM["ENDOSO_DE_TITULOS"] = "21";
})(PAYMENT_METHOD_CODE_ENUM || (PAYMENT_METHOD_CODE_ENUM = {}));
