import { CODIGO_RETENCION_ENUM } from "../enums/codigo-retencion.enum";

export const TarifaRetencionXml: Record<CODIGO_RETENCION_ENUM, number> = {
  // IVA
  [CODIGO_RETENCION_ENUM.IVA_CIENTO_POR_CIENTO_RESOLUCION]: 1,
  [CODIGO_RETENCION_ENUM.IVA_DOCE_POR_CIENTO_PRESUNTIVO_EDITORES]: 0.12,
  [CODIGO_RETENCION_ENUM.IVA_CIENTO_POR_CIENTO_DISTRIBUIDORES]: 100,
  [CODIGO_RETENCION_ENUM.IVA_CIENTO_POR_CIENTO_VOCEADORES]: 100,

  // Renta
  [CODIGO_RETENCION_ENUM.RENTA_DOS_POR_MIL]: 0.2,
  [CODIGO_RETENCION_ENUM.RENTA_TRES_POR_MIL]: 0.2,
};
