export type ErrorCode =
  | "UANATACA_CERT_NOT_FOUND"
  | "SIGNING_KEY_NOT_FOUND"
  | "PRIVATE_KEY_EXTRACTION_ERROR"
  | "UNKNOWN_SIGN_STRATEGY"
  | "SIGN_STRATEGY_ERROR"
  | "INFRASTRUCTURE_ERROR"
  | "UNHANDLED_ERROR"
  | "UNKNOWN_ERROR"
  | "P12_PASSWORD_ERROR"
  | "P12_STRUCTURE_ERROR"
  | "XML_STRUCTURE_ERROR";
