export var CONTRIBUYENTE_RIMPE_ENUM;
(function (CONTRIBUYENTE_RIMPE_ENUM) {
    CONTRIBUYENTE_RIMPE_ENUM["RIMPE_GENERAL"] = "CONTRIBUYENTE R\u00C9GIMEN RIMPE";
    CONTRIBUYENTE_RIMPE_ENUM["RIMPE_POPULAR"] = "CONTRIBUYENTE NEGOCIO POPULAR - R\u00C9GIMEN RIMPE";
})(CONTRIBUYENTE_RIMPE_ENUM || (CONTRIBUYENTE_RIMPE_ENUM = {}));
