export var IDENTIFICATION_CODE_ENUM;
(function (IDENTIFICATION_CODE_ENUM) {
    IDENTIFICATION_CODE_ENUM["RUC"] = "04";
    IDENTIFICATION_CODE_ENUM["CEDULA"] = "05";
    IDENTIFICATION_CODE_ENUM["PASAPORTE"] = "06";
    IDENTIFICATION_CODE_ENUM["CONSUMIDOR_FINAL"] = "07";
    IDENTIFICATION_CODE_ENUM["EXTERIOR"] = "08";
})(IDENTIFICATION_CODE_ENUM || (IDENTIFICATION_CODE_ENUM = {}));
