export var IMPUESTO_A_RETENER_ENUM;
(function (IMPUESTO_A_RETENER_ENUM) {
    IMPUESTO_A_RETENER_ENUM[IMPUESTO_A_RETENER_ENUM["IVA_PRESUNTIVO_Y_RENTA"] = 4] = "IVA_PRESUNTIVO_Y_RENTA";
})(IMPUESTO_A_RETENER_ENUM || (IMPUESTO_A_RETENER_ENUM = {}));
