export var OBLIGADO_CONTABILIDAD_ENUM;
(function (OBLIGADO_CONTABILIDAD_ENUM) {
    OBLIGADO_CONTABILIDAD_ENUM["SI"] = "SI";
    OBLIGADO_CONTABILIDAD_ENUM["NO"] = "NO";
})(OBLIGADO_CONTABILIDAD_ENUM || (OBLIGADO_CONTABILIDAD_ENUM = {}));
